[package]
name = "wealth_manager"
version = "0.1.0"
authors = ["denilson"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
serde_json = "1.0.108"
chrono = "0.4.31"
rand = "0.8.5"
